#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  force_global_config = true

  bootstrap_before = "init#before"
  bootstrap_after = "init#after"

  colorscheme = "nord"
  colorscheme_bg = "dark"
  enable_guicolors = true

  statusline_separator = "arrow"
  statusline_iseparator = "bar"
  buffer_index_type = 4
  windows_index_type = 3
  enable_tabline_filetype_icon = true
  enable_statusline_mode = true
  statusline_unicode = true
  
  # nerdtree
  filetree_direction = "left"

  autocomplete_method = "coc"

[[custom_plugins]]
  repo = "kotoji/nord-vim"
  merged = false

# Disabled for coc
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"
  enable = false

[[custom_plugins]]
  name = 'neoclide/coc.nvim'
  merged = 0

[[custom_plugins]]
  name = 'SirVer/ultisnips'
  merged = 0

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = 'lang#scala'
  enable = false

[[custom_plugins]]
  name = 'derekwyatt/vim-scala'
  merged = 0

[[layers]]
  name = 'lang#rust'

