#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  force_global_config = true

  bootstrap_before = "init#before"
  bootstrap_after = "init#after"

  colorscheme = "nord"
  colorscheme_bg = "dark"
  enable_guicolors = true

  statusline_separator = "arrow"
  statusline_iseparator = "bar"
  buffer_index_type = 4
  windows_index_type = 3
  enable_tabline_filetype_icon = true
  enable_statusline_mode = true
  statusline_unicode = true
  
  # nerdtree
  filetree_direction = "left"

  autocomplete_method = "deoplete"

[[custom_plugins]]
  repo = "kotoji/nord-vim"
  merged = false

[[layers]]
  # NOTE: このレイヤーのせいで起動時にエラーが表示されるが今のところ動作に問題はないのでスルーしている
  name = 'lsp'
  enabled_clients = ['metals']

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"

[[custom_plugins]]
  name = 'neoclide/coc.nvim'
  merged = 0

[[custom_plugins]]
  name = 'voldikss/vim-floaterm'
  merged = 0

[[custom_plugins]]
  name = 'SirVer/ultisnips'
  merged = 0

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  # self customized layer
  # TODO: キーマップをちゃんと設定する
  #   とりあえず ↓ の人の設定を丸パクリしている (vim-metals のところだけ)
  #   https://creators-note.chatwork.com/entry/2022/03/28/083000
  name = 'lang#scala'

[[layers]]
  # self customized layer
  name = 'lang#rust'
  format_on_save = true

[[layers]]
  name = 'lang#go'
  format_on_save = true

[[layers]]
  name = "lang#clojure"
  clojure_interpreter = "lein repl"

[[layers]]
  # self made layer
  name= "lang#hcl"
  terraform_fmt_on_save = true

